# Generated by Django 5.0.1 on 2024-01-12 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("unique_name", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_type", models.CharField(max_length=32)),
                ("charge_type", models.CharField(max_length=32)),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.IntegerField()),
                ("source", models.CharField(max_length=16)),
                ("destination", models.CharField(max_length=16)),
                ("departure_time_stamp", models.DateTimeField()),
                ("arrival_time_stamp", models.DateTimeField()),
                ("flight_class", models.CharField(max_length=16)),
                ("number_of_stops", models.IntegerField()),
                ("fare_basis", models.CharField(max_length=255)),
                ("ticket_type", models.CharField(max_length=16)),
                ("onward_ticket", models.BooleanField(default=False)),
                ("return_ticket", models.BooleanField(default=False)),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.carrier"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlightPacket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pricing_currency", models.CharField(max_length=16)),
                ("request_time", models.DateTimeField()),
                ("flights", models.ManyToManyField(to="app.flight")),
                ("service_charges", models.ManyToManyField(to="app.servicecharge")),
            ],
        ),
    ]
