# Generated by Django 5.0.1 on 2024-01-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flightpacket",
            name="request_time",
        ),
        migrations.AlterField(
            model_name="flightpacket",
            name="flights",
            field=models.ManyToManyField(blank=True, to="app.flight"),
        ),
        migrations.AlterField(
            model_name="servicecharge",
            name="price",
            field=models.CharField(max_length=255),
        ),
    ]
