# Generated by Django 5.0.1 on 2024-01-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_flight_carrier_alter_flight_arrival_time_stamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="added_to_flight",
            field=models.BooleanField(default=False),
        ),
    ]
