# Generated by Django 5.0.1 on 2024-01-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_flight_added_to_flight"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecharge",
            name="added_to_flight",
            field=models.BooleanField(default=False),
        ),
    ]
