# Generated by Django 5.0.1 on 2024-01-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_servicecharge_added_to_flight"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightpacket",
            name="request_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
